In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_excel('HDI_DATASET.xlsx',header=1)
df.head(33)

,Year,GDP per Capita (Constant 2015 US$),LIFE EXPECTANCY,MEAN YEARS OF SCHOOLING
0,1990,537.9,59,2.8
1,1991,531.9,59,2.9
2,1992,549.2,59,3.0
3,1993,563.4,60,3.1
4,1994,588.7,60,3.2
5,1995,620.7,61,3.3
6,1996,654.4,61,3.5
7,1997,667.6,61,3.6
8,1998,695.3,62,3.8
9,1999,742.5,62,4.0
10,2000,756.7,63,4.1
11,2001,778.5,63,4.2
12,2002,793.6,64,4.3
13,2003,841.3,64,4.4
14,2004,892.6,64,4.5
15,2005,947.7,65,4.5
16,2006,1008.2,65,4.6
17,2007,1069.2,66,4.7
18,2008,1086.5,66,4.8
19,2009,1155.1,67,5.0
20,2010,1235.2,67,5.1
21,2011,1281.6,68,5.3
22,2012,1333.1,68,5.4
23,2013,1399.5,68,5.5
24,2014,1484.3,69,5.6
25,2015,1584.0,69,5.7
26,2016,1694.5,70,5.8
27,2017,1788.7,70,6.0
28,2018,1883.4,70,6.2
29,2019,1936.0,71,6.3
30,2020,1806.5,70,6.5
31,2021,1965.3,67,6.5
32,2022,2098.2,72,6.6

In [ ]:
def calculate_crafts_income_utility(y, y_star=5120):

    # Define conditions for the piecewise segments
    conditions = [
        (y <= y_star),
        (y > y_star) & (y <= 2 * y_star),
        (y > 2 * y_star) & (y <= 3 * y_star),
        (y > 3 * y_star)
    ]

    # Define the corresponding formulas for each bracket
    choices = [
        y,
        y_star + 2 * (y - y_star) ** (1 / 2),
        y_star + 2 * (y_star) ** (1 / 2)
            + 3 * (y - 2 * y_star) ** (1 / 3),
        (
            y_star
            + 2 * (y_star) ** (1 / 2)
            + 3 * (y_star) ** (1 / 3)
            + 4 * (y - 3 * y_star) ** (1 / 4)
        )
    ]

    return np.select(conditions, choices, default=np.nan)

In [ ]:
# 1. Clean raw values (Run this BEFORE any normalization)
df.columns = df.columns.str.strip()
df.head(33)

,Year,GDP per Capita (Constant 2015 US$),LIFE EXPECTANCY,MEAN YEARS OF SCHOOLING
0,1990,537.9,59,2.8
1,1991,531.9,59,2.9
2,1992,549.2,59,3.0
3,1993,563.4,60,3.1
4,1994,588.7,60,3.2
5,1995,620.7,61,3.3
6,1996,654.4,61,3.5
7,1997,667.6,61,3.6
8,1998,695.3,62,3.8
9,1999,742.5,62,4.0
10,2000,756.7,63,4.1
11,2001,778.5,63,4.2
12,2002,793.6,64,4.3
13,2003,841.3,64,4.4
14,2004,892.6,64,4.5
15,2005,947.7,65,4.5
16,2006,1008.2,65,4.6
17,2007,1069.2,66,4.7
18,2008,1086.5,66,4.8
19,2009,1155.1,67,5.0
20,2010,1235.2,67,5.1
21,2011,1281.6,68,5.3
22,2012,1333.1,68,5.4
23,2013,1399.5,68,5.5
24,2014,1484.3,69,5.6
25,2015,1584.0,69,5.7
26,2016,1694.5,70,5.8
27,2017,1788.7,70,6.0
28,2018,1883.4,70,6.2
29,2019,1936.0,71,6.3
30,2020,1806.5,70,6.5
31,2021,1965.3,67,6.5
32,2022,2098.2,72,6.6

In [ ]:
# 2. Compute the piecewise Adjusted Income on RAW GDP values
df["adjusted_income"] = calculate_crafts_income_utility(df['GDP per Capita (Constant 2015 US$)'], y_star=5120)
df.head(33)

,Year,GDP per Capita (Constant 2015 US$),LIFE EXPECTANCY,MEAN YEARS OF SCHOOLING,adjusted_income
0,1990,537.9,59,2.8,537.9
1,1991,531.9,59,2.9,531.9
2,1992,549.2,59,3.0,549.2
3,1993,563.4,60,3.1,563.4
4,1994,588.7,60,3.2,588.7
5,1995,620.7,61,3.3,620.7
6,1996,654.4,61,3.5,654.4
7,1997,667.6,61,3.6,667.6
8,1998,695.3,62,3.8,695.3
9,1999,742.5,62,4.0,742.5
10,2000,756.7,63,4.1,756.7
11,2001,778.5,63,4.2,778.5
12,2002,793.6,64,4.3,793.6
13,2003,841.3,64,4.4,841.3
14,2004,892.6,64,4.5,892.6
15,2005,947.7,65,4.5,947.7
16,2006,1008.2,65,4.6,1008.2
17,2007,1069.2,66,4.7,1069.2
18,2008,1086.5,66,4.8,1086.5
19,2009,1155.1,67,5.0,1155.1
20,2010,1235.2,67,5.1,1235.2
21,2011,1281.6,68,5.3,1281.6
22,2012,1333.1,68,5.4,1333.1
23,2013,1399.5,68,5.5,1399.5
24,2014,1484.3,69,5.6,1484.3
25,2015,1584.0,69,5.7,1584.0
26,2016,1694.5,70,5.8,1694.5
27,2017,1788.7,70,6.0,1788.7
28,2018,1883.4,70,6.2,1883.4
29,2019,1936.0,71,6.3,1936.0
30,2020,1806.5,70,6.5,1806.5
31,2021,1965.3,67,6.5,1965.3
32,2022,2098.2,72,6.6,2098.2

In [ ]:
# 3. Apply Fixed Goalpost Normalization to ALL variables
df["health_index"] = (df["LIFE EXPECTANCY"] - 25) / (85 - 25)
df["education_index"] = (df["MEAN YEARS OF SCHOOLING"] - 0) / (15 - 0)
df["income_index"] = (df["adjusted_income"] - 200) / (5385 - 200)
df.head(33)

,Year,GDP per Capita (Constant 2015 US$),LIFE EXPECTANCY,MEAN YEARS OF SCHOOLING,adjusted_income,health_index,education_index,income_index
0,1990,537.9,59,2.8,537.9,0.566667,0.186667,0.065169
1,1991,531.9,59,2.9,531.9,0.566667,0.193333,0.064012
2,1992,549.2,59,3.0,549.2,0.566667,0.200000,0.067348
3,1993,563.4,60,3.1,563.4,0.583333,0.206667,0.070087
4,1994,588.7,60,3.2,588.7,0.583333,0.213333,0.074966
5,1995,620.7,61,3.3,620.7,0.600000,0.220000,0.081138
6,1996,654.4,61,3.5,654.4,0.600000,0.233333,0.087637
7,1997,667.6,61,3.6,667.6,0.600000,0.240000,0.090183
8,1998,695.3,62,3.8,695.3,0.616667,0.253333,0.095526
9,1999,742.5,62,4.0,742.5,0.616667,0.266667,0.104629
10,2000,756.7,63,4.1,756.7,0.633333,0.273333,0.107367
11,2001,778.5,63,4.2,778.5,0.633333,0.280000,0.111572
12,2002,793.6,64,4.3,793.6,0.650000,0.286667,0.114484
13,2003,841.3,64,4.4,841.3,0.650000,0.293333,0.123684
14,2004,892.6,64,4.5,892.6,0.650000,0.300000,0.133578
15,2005,947.7,65,4.5,947.7,0.666667,0.300000,0.144204
16,2006,1008.2,65,4.6,1008.2,0.666667,0.306667,0.155873
17,2007,1069.2,66,4.7,1069.2,0.683333,0.313333,0.167637
18,2008,1086.5,66,4.8,1086.5,0.683333,0.320000,0.170974
19,2009,1155.1,67,5.0,1155.1,0.700000,0.333333,0.184204
20,2010,1235.2,67,5.1,1235.2,0.700000,0.340000,0.199653
21,2011,1281.6,68,5.3,1281.6,0.716667,0.353333,0.208602
22,2012,1333.1,68,5.4,1333.1,0.716667,0.360000,0.218534
23,2013,1399.5,68,5.5,1399.5,0.716667,0.366667,0.231340
24,2014,1484.3,69,5.6,1484.3,0.733333,0.373333,0.247695
25,2015,1584.0,69,5.7,1584.0,0.733333,0.380000,0.266924
26,2016,1694.5,70,5.8,1694.5,0.750000,0.386667,0.288235
27,2017,1788.7,70,6.0,1788.7,0.750000,0.400000,0.306403
28,2018,1883.4,70,6.2,1883.4,0.750000,0.413333,0.324667
29,2019,1936.0,71,6.3,1936.0,0.766667,0.420000,0.334812
30,2020,1806.5,70,6.5,1806.5,0.750000,0.433333,0.309836
31,2021,1965.3,67,6.5,1965.3,0.700000,0.433333,0.340463
32,2022,2098.2,72,6.6,2098.2,0.783333,0.440000,0.366095

In [ ]:
# 4. Calculate the true, unskewed Historical HDI
df['HDI_1'] = (1/3 * df['health_index']) + (1/3 * df['education_index']) + (1/3 * df['income_index'])
df.head(33)

,Year,GDP per Capita (Constant 2015 US$),LIFE EXPECTANCY,MEAN YEARS OF SCHOOLING,adjusted_income,health_index,education_index,income_index,HDI_1
0,1990,537.9,59,2.8,537.9,0.566667,0.186667,0.065169,0.272834
1,1991,531.9,59,2.9,531.9,0.566667,0.193333,0.064012,0.274671
2,1992,549.2,59,3.0,549.2,0.566667,0.200000,0.067348,0.278005
3,1993,563.4,60,3.1,563.4,0.583333,0.206667,0.070087,0.286696
4,1994,588.7,60,3.2,588.7,0.583333,0.213333,0.074966,0.290544
5,1995,620.7,61,3.3,620.7,0.600000,0.220000,0.081138,0.300379
6,1996,654.4,61,3.5,654.4,0.600000,0.233333,0.087637,0.306990
7,1997,667.6,61,3.6,667.6,0.600000,0.240000,0.090183,0.310061
8,1998,695.3,62,3.8,695.3,0.616667,0.253333,0.095526,0.321842
9,1999,742.5,62,4.0,742.5,0.616667,0.266667,0.104629,0.329321
10,2000,756.7,63,4.1,756.7,0.633333,0.273333,0.107367,0.338011
11,2001,778.5,63,4.2,778.5,0.633333,0.280000,0.111572,0.341635
12,2002,793.6,64,4.3,793.6,0.650000,0.286667,0.114484,0.350384
13,2003,841.3,64,4.4,841.3,0.650000,0.293333,0.123684,0.355672
14,2004,892.6,64,4.5,892.6,0.650000,0.300000,0.133578,0.361193
15,2005,947.7,65,4.5,947.7,0.666667,0.300000,0.144204,0.370290
16,2006,1008.2,65,4.6,1008.2,0.666667,0.306667,0.155873,0.376402
17,2007,1069.2,66,4.7,1069.2,0.683333,0.313333,0.167637,0.388101
18,2008,1086.5,66,4.8,1086.5,0.683333,0.320000,0.170974,0.391436
19,2009,1155.1,67,5.0,1155.1,0.700000,0.333333,0.184204,0.405846
20,2010,1235.2,67,5.1,1235.2,0.700000,0.340000,0.199653,0.413218
21,2011,1281.6,68,5.3,1281.6,0.716667,0.353333,0.208602,0.426201
22,2012,1333.1,68,5.4,1333.1,0.716667,0.360000,0.218534,0.431734
23,2013,1399.5,68,5.5,1399.5,0.716667,0.366667,0.231340,0.438225
24,2014,1484.3,69,5.6,1484.3,0.733333,0.373333,0.247695,0.451454
25,2015,1584.0,69,5.7,1584.0,0.733333,0.380000,0.266924,0.460086
26,2016,1694.5,70,5.8,1694.5,0.750000,0.386667,0.288235,0.474967
27,2017,1788.7,70,6.0,1788.7,0.750000,0.400000,0.306403,0.485468
28,2018,1883.4,70,6.2,1883.4,0.750000,0.413333,0.324667,0.496000
29,2019,1936.0,71,6.3,1936.0,0.766667,0.420000,0.334812,0.507160
30,2020,1806.5,70,6.5,1806.5,0.750000,0.433333,0.309836,0.497723
31,2021,1965.3,67,6.5,1965.3,0.700000,0.433333,0.340463,0.491265
32,2022,2098.2,72,6.6,2098.2,0.783333,0.440000,0.366095,0.529809

In [ ]:

print(df[['Year', 'health_index', 'education_index', 'income_index', 'HDI_1']].head(33))

    Year  health_index  education_index  income_index     HDI_1
0   1990      0.566667         0.186667      0.065169  0.272834
1   1991      0.566667         0.193333      0.064012  0.274671
2   1992      0.566667         0.200000      0.067348  0.278005
3   1993      0.583333         0.206667      0.070087  0.286696
4   1994      0.583333         0.213333      0.074966  0.290544
5   1995      0.600000         0.220000      0.081138  0.300379
6   1996      0.600000         0.233333      0.087637  0.306990
7   1997      0.600000         0.240000      0.090183  0.310061
8   1998      0.616667         0.253333      0.095526  0.321842
9   1999      0.616667         0.266667      0.104629  0.329321
10  2000      0.633333         0.273333      0.107367  0.338011
11  2001      0.633333         0.280000      0.111572  0.341635
12  2002      0.650000         0.286667      0.114484  0.350384
13  2003      0.650000         0.293333      0.123684  0.355672
14  2004      0.650000         0.300000      0.133578  0.361193
15  2005      0.666667         0.300000      0.144204  0.370290
16  2006      0.666667         0.306667      0.155873  0.376402
17  2007      0.683333         0.313333      0.167637  0.388101
18  2008      0.683333         0.320000      0.170974  0.391436
19  2009      0.700000         0.333333      0.184204  0.405846
20  2010      0.700000         0.340000      0.199653  0.413218
21  2011      0.716667         0.353333      0.208602  0.426201
22  2012      0.716667         0.360000      0.218534  0.431734
23  2013      0.716667         0.366667      0.231340  0.438225
24  2014      0.733333         0.373333      0.247695  0.451454
25  2015      0.733333         0.380000      0.266924  0.460086
26  2016      0.750000         0.386667      0.288235  0.474967
27  2017      0.750000         0.400000      0.306403  0.485468
28  2018      0.750000         0.413333      0.324667  0.496000
29  2019      0.766667         0.420000      0.334812  0.507160
30  2020      0.750000         0.433333      0.309836  0.497723
31  2021      0.700000         0.433333      0.340463  0.491265
32  2022      0.783333         0.440000      0.366095  0.529809

In [ ]:

# NON-INCOME HDI 1
# Arithmetic mean of Health and Education

df["NIHDI1"] = (
    df["health_index"] + df["education_index"]
) / 2

# Display the result
df[["Year", "health_index", "education_index", "NIHDI1"]].head(33)

    Year  health_index  education_index    NIHDI1
0   1990      0.566667         0.186667  0.376667
1   1991      0.566667         0.193333  0.380000
2   1992      0.566667         0.200000  0.383333
3   1993      0.583333         0.206667  0.395000
4   1994      0.583333         0.213333  0.398333
5   1995      0.600000         0.220000  0.410000
6   1996      0.600000         0.233333  0.416667
7   1997      0.600000         0.240000  0.420000
8   1998      0.616667         0.253333  0.435000
9   1999      0.616667         0.266667  0.441667
10  2000      0.633333         0.273333  0.453333
11  2001      0.633333         0.280000  0.456667
12  2002      0.650000         0.286667  0.468333
13  2003      0.650000         0.293333  0.471667
14  2004      0.650000         0.300000  0.475000
15  2005      0.666667         0.300000  0.483333
16  2006      0.666667         0.306667  0.486667
17  2007      0.683333         0.313333  0.498333
18  2008      0.683333         0.320000  0.501667
19  2009      0.700000         0.333333  0.516667
20  2010      0.700000         0.340000  0.520000
21  2011      0.716667         0.353333  0.535000
22  2012      0.716667         0.360000  0.538333
23  2013      0.716667         0.366667  0.541667
24  2014      0.733333         0.373333  0.553333
25  2015      0.733333         0.380000  0.556667
26  2016      0.750000         0.386667  0.568333
27  2017      0.750000         0.400000  0.575000
28  2018      0.750000         0.413333  0.581667
29  2019      0.766667         0.420000  0.593333
30  2020      0.750000         0.433333  0.591667
31  2021      0.700000         0.433333  0.566667
32  2022      0.783333         0.440000  0.611667

In [ ]:
ts1 = df[[
    "Year",
    "GDP per Capita (Constant 2015 US$)",
    "HDI_1",
    "NIHDI1"
]].copy()

ts1.head()

   Year  GDP per Capita (Constant 2015 US$)     HDI_1    NIHDI1
0  1990                               537.9  0.272834  0.376667
1  1991                               531.9  0.274671  0.380000
2  1992                               549.2  0.278005  0.383333
3  1993                               563.4  0.286696  0.395000
4  1994                               588.7  0.290544  0.398333

In [ ]:
#saving the data
ts1.to_csv("ts_HDI1.csv", index=False)