In [ ]:
import pandas as pd
import numpy as np

df = pd.read_excel("HDI_DATASET.xlsx", header=1)
df.columns = df.columns.str.strip()

# WE USE KAKWANI TRANSFORMATION TO CALCULATE HDI_3
def kakwani_transform(x, minimum, maximum):
    return (
        np.log(maximum - minimum)
        - np.log(maximum - x)
    ) / np.log(maximum - minimum)


def calculate_hdi3(df):

    output_df = df.copy()

    # Goalposts
    LE_MIN, LE_MAX = 20.0, 85.0
    SCH_MIN, SCH_MAX = 0.0, 15.0

    # Income goalposts used by UNDP
    INC_MIN, INC_MAX = 100.0, 75000.0

    # Kakwani convex transformation
    output_df["education_index"] = kakwani_transform(
        output_df["MEAN YEARS OF SCHOOLING"],
        SCH_MIN,
        SCH_MAX
    )

    output_df["health_index"] = kakwani_transform(
        output_df["LIFE EXPECTANCY"],
        LE_MIN,
        LE_MAX
    )

    # Logarithmic income transformation
    income = np.clip(
        output_df["GDP per Capita (Constant 2015 US$)"],
        INC_MIN,
        INC_MAX
    )

    output_df["income_index"] = (
        np.log(income) - np.log(INC_MIN)
    ) / (
        np.log(INC_MAX) - np.log(INC_MIN)
    )

    # Geometric mean
    output_df["HDI3"] = (
        output_df["education_index"]
        * output_df["health_index"]
        * output_df["income_index"]
    ) ** (1 / 3)

    return output_df


HDI_3 = calculate_hdi3(df)

HDI_3[
    ["Year", "education_index", "health_index", "income_index", "HDI3"]
].head(33)

    Year  education_index  health_index  income_index      HDI3
0   1990         0.076296      0.219503      0.254152  0.162061
1   1991         0.079336      0.219503      0.252457  0.163819
2   1992         0.082400      0.219503      0.257292  0.166955
3   1993         0.085490      0.228899      0.261148  0.172246
4   1994         0.088606      0.228899      0.267784  0.175778
5   1995         0.091749      0.238678      0.275779  0.182106
6   1996         0.098116      0.238678      0.283766  0.188005
7   1997         0.101341      0.238678      0.286782  0.190714
8   1998         0.107877      0.248873      0.292923  0.198863
9   1999         0.114531      0.248873      0.302844  0.205135
10  2000         0.117903      0.259522      0.305706  0.210702
11  2001         0.121306      0.259522      0.309996  0.213700
12  2002         0.124742      0.270666      0.312898  0.219423
13  2003         0.128209      0.270666      0.321715  0.223498
14  2004         0.131709      0.270666      0.330656  0.227584
15  2005         0.131709      0.282354      0.339704  0.232900
16  2006         0.135243      0.282354      0.349052  0.237101
17  2007         0.138811      0.294642      0.357926  0.244626
18  2008         0.142413      0.294642      0.360350  0.247281
19  2009         0.149726      0.307594      0.369599  0.257238
20  2010         0.153437      0.307594      0.379727  0.261694
21  2011         0.160973      0.321286      0.385297  0.271111
22  2012         0.164800      0.321286      0.391248  0.274642
23  2013         0.168667      0.321286      0.398591  0.278494
24  2014         0.172575      0.335809      0.407477  0.286896
25  2015         0.176524      0.335809      0.417297  0.291372
26  2016         0.180516      0.351270      0.427484  0.300395
27  2017         0.188632      0.351270      0.435656  0.306761
28  2018         0.196931      0.351270      0.443449  0.313040
29  2019         0.201151      0.367798      0.447610  0.321127
30  2020         0.209739      0.351270      0.437152  0.318164
31  2021         0.209739      0.307594      0.449879  0.307315
32  2022         0.214109      0.385551      0.459763  0.336060

In [ ]:
# NON-INCOME HDI 3
# Geometric mean of transformed Education and Health
HDI_3["NIHDI3"] = (
    HDI_3["education_index"] * HDI_3["health_index"]
) ** (1 / 2)

# Display the result
HDI_3[["Year", "education_index", "health_index", "NIHDI3"]].head(33)

    Year  education_index  health_index    NIHDI3
0   1990         0.076296      0.219503  0.129411
1   1991         0.079336      0.219503  0.131964
2   1992         0.082400      0.219503  0.134488
3   1993         0.085490      0.228899  0.139888
4   1994         0.088606      0.228899  0.142414
5   1995         0.091749      0.238678  0.147981
6   1996         0.098116      0.238678  0.153030
7   1997         0.101341      0.238678  0.155525
8   1998         0.107877      0.248873  0.163853
9   1999         0.114531      0.248873  0.168830
10  2000         0.117903      0.259522  0.174924
11  2001         0.121306      0.259522  0.177431
12  2002         0.124742      0.270666  0.183748
13  2003         0.128209      0.270666  0.186284
14  2004         0.131709      0.270666  0.188810
15  2005         0.131709      0.282354  0.192843
16  2006         0.135243      0.282354  0.195413
17  2007         0.138811      0.294642  0.202236
18  2008         0.142413      0.294642  0.204844
19  2009         0.149726      0.307594  0.214604
20  2010         0.153437      0.307594  0.217247
21  2011         0.160973      0.321286  0.227417
22  2012         0.164800      0.321286  0.230104
23  2013         0.168667      0.321286  0.232788
24  2014         0.172575      0.335809  0.240733
25  2015         0.176524      0.335809  0.243472
26  2016         0.180516      0.351270  0.251813
27  2017         0.188632      0.351270  0.257412
28  2018         0.196931      0.351270  0.263013
29  2019         0.201151      0.367798  0.271998
30  2020         0.209739      0.351270  0.271432
31  2021         0.209739      0.307594  0.253997
32  2022         0.214109      0.385551  0.287315

In [ ]:
ts3 = HDI_3[[
    "Year",
    "HDI3",
    "NIHDI3"
]].copy()

ts3.to_csv("ts_HDI3.csv", index=False)